# Generated by Django 4.2.21 on 2025-06-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubeview', '0004_userdatabaseconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatabaseconnection',
            name='check_frequency',
            field=models.CharField(choices=[('minute', 'Every Minute'), ('hour', 'Every Hour'), ('day', 'Every Day')], default='hour', max_length=10),
        ),
        migrations.AddField(
            model_name='userdatabaseconnection',
            name='db_type',
            field=models.CharField(default='postgres', max_length=50),
        ),
        migrations.AddField(
            model_name='userdatabaseconnection',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
