# Generated by Django 4.2.21 on 2025-06-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubeview', '0006_user_check_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdatabaseconnection',
            name='check_frequency',
        ),
        migrations.RemoveField(
            model_name='userdatabaseconnection',
            name='database',
        ),
        migrations.RemoveField(
            model_name='userdatabaseconnection',
            name='db_password',
        ),
        migrations.RemoveField(
            model_name='userdatabaseconnection',
            name='db_user',
        ),
        migrations.RemoveField(
            model_name='userdatabaseconnection',
            name='last_checked_at',
        ),
        migrations.AddField(
            model_name='userdatabaseconnection',
            name='database_name',
            field=models.CharField(default='default_db', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdatabaseconnection',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdatabaseconnection',
            name='name',
            field=models.CharField(default='default_connection', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdatabaseconnection',
            name='password',
            field=models.CharField(default='default_pass', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdatabaseconnection',
            name='username',
            field=models.CharField(default='default_user', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdatabaseconnection',
            name='db_type',
            field=models.CharField(max_length=50),
        ),
    ]
