# Generated by Django 5.2.3 on 2025-07-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubeview', '0007_remove_userdatabaseconnection_check_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(default='Custom', max_length=50),
        ),
    ]
