# Generated by Django 5.2.3 on 2025-07-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubeview', '0008_incident_incident_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
