# Generated by Django 5.2.3 on 2025-07-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubeview', '0009_incident_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportedmetadata',
            name='ai_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
