# Generated by Django 5.2.3 on 2025-07-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubeview', '0010_exportedmetadata_ai_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='severity',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20, null=True),
        ),
    ]
