# Generated by Django 5.2.3 on 2025-07-04 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubeview', '0011_incident_severity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('null_count', models.IntegerField(default=0)),
                ('null_percentage', models.FloatField(default=0)),
                ('distinct_count', models.IntegerField(default=0)),
                ('min_value', models.CharField(blank=True, max_length=255, null=True)),
                ('max_value', models.CharField(blank=True, max_length=255, null=True)),
                ('avg_value', models.FloatField(blank=True, null=True)),
                ('most_frequent', models.CharField(blank=True, max_length=255, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubeview.columnmetadata')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubeview.datatable')),
            ],
            options={
                'unique_together': {('table', 'column')},
            },
        ),
    ]
