# Generated by Django 5.2.3 on 2025-07-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubeview', '0012_fieldmetric'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatable',
            old_name='owner',
            new_name='user',
        ),
    ]
