# Generated by Django 5.2.3 on 2025-07-04 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubeview', '0013_rename_owner_datatable_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataqualitycheck',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_quality_checks', to='cubeview.datatable'),
        ),
    ]
